apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: custom-redis
  namespace: demo
spec:
  version: "4.0-v1"
  configSource:
      configMap:
        name: rd-custom-config
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
