apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-infant
  namespace: demo
spec:
  version: "3.4-v1"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
