apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-demo
  labels:
    kubedb: cli-demo
spec:
  version: "4.0-v1"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
