#######################################
#     Base Image for postgres DB      #
#   Image: appscode/postgres:9.5-db   #
#######################################

FROM appscode/gosu:8.5

RUN groupadd -r postgres --gid=999 && useradd -r -g postgres --uid=999 postgres
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

ENV PG_MAJOR 9.5
ENV PG_VERSION 9.5.2-1.pgdg80+1
ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH
ENV PGROOT /var/pv
ENV PGDATA /var/pv/data
ENV MW_SENDER 3
ENV WK_SEGMENTS 50
ENV ARC_TIME 1800

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list

RUN set -x \
  && apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates postgresql-common netcat \
	&& sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
	&& apt-get install -y  --no-install-recommends \
		postgresql-$PG_MAJOR \
		postgresql-contrib-$PG_MAJOR

RUN set -x \
    && apt-get update \
	&& apt-get install -y --no-install-recommends lzop pv daemontools python-setuptools python-pip python-dev build-essential git python-psycopg2 \
	&& easy_install --upgrade pip \
	&& pip install requests --upgrade \
	&& pip install six --upgrade \
	&& pip install pyasn1 --upgrade \
	&& pip install git+https://github.com/wal-e/wal-e.git \
	&& rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man /tmp/*

RUN mkdir /scripts
COPY scripts /scripts/
ENTRYPOINT ["/scripts/run.sh"]
EXPOSE 5432
