#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars
echo "Starting Db..."

sv start influxd || exit 1

set -o errexit
set -o nounset
set -o pipefail

if [ -f '/srv/influxdb/secrets/.admin' ]; then
        export $(cat /srv/influxdb/secrets/.admin | xargs)
else
    echo
    echo 'Missing environment file /srv/influxdb/secrets/.admin.'
    echo
    exit 1
fi

# use local influxdb
INFLUX_HOST=127.0.0.1
INFLUX_API_PORT=8086
if [ -n "${INFLUX_ADMIN_USER}" ]; then
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -execute "CREATE USER ${INFLUX_ADMIN_USER} WITH PASSWORD '${INFLUX_ADMIN_PASSWORD}' WITH ALL PRIVILEGES"
    retval=$?
    if [ "$retval" -ne 0 ]; then
        exit 1
    fi
fi

if [ -n "${INFLUX_WRITE_USER}" ]; then
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -username ${INFLUX_ADMIN_USER} -password ${INFLUX_ADMIN_PASSWORD} -execute "CREATE DATABASE ${INFLUX_DB}"
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -username ${INFLUX_ADMIN_USER} -password ${INFLUX_ADMIN_PASSWORD} -execute "CREATE USER ${INFLUX_WRITE_USER} WITH PASSWORD '${INFLUX_WRITE_PASSWORD}'"
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -username ${INFLUX_ADMIN_USER} -password ${INFLUX_ADMIN_PASSWORD} -execute "GRANT WRITE ON ${INFLUX_DB} TO ${INFLUX_WRITE_USER}"
fi

if [ -n "${INFLUX_READ_USER}" ]; then
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -username ${INFLUX_ADMIN_USER} -password ${INFLUX_ADMIN_PASSWORD} -execute "CREATE USER ${INFLUX_READ_USER} WITH PASSWORD '${INFLUX_READ_PASSWORD}'"
    influx -host ${INFLUX_HOST} -port ${INFLUX_API_PORT} -username ${INFLUX_ADMIN_USER} -password ${INFLUX_ADMIN_PASSWORD} -execute "GRANT READ ON ${INFLUX_DB} TO ${INFLUX_READ_USER}"
fi

rm -rf /etc/service/db
echo "Database and users created.."
echo "Service deleted...."
