apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: p1
  namespace: demo
spec:
  version: 9.6.5
  replicas: 2
  standby: hot
  doNotPause: false
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        endpoint: 's3.amazonaws.com'
        bucket: kubedb
  storage:
    resources:
      requests:
        storage: 50Mi
