apiVersion: apps.k8s.appscode.com/v1
kind: PetSet
metadata:
  creationTimestamp: "2025-11-06T05:52:02Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mds
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mariadbs.kubedb.com
  managedFields:
  - apiVersion: apps.k8s.appscode.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"dde7ad7f-87fe-44f1-8c7b-d542f8cb1309"}: {}
      f:spec:
        .: {}
        f:podManagementPolicy: {}
        f:podPlacementPolicy: {}
        f:replicas: {}
        f:selector: {}
        f:serviceName: {}
        f:template:
          .: {}
          f:metadata:
            .: {}
            f:labels:
              .: {}
              f:app.kubernetes.io/component: {}
              f:app.kubernetes.io/instance: {}
              f:app.kubernetes.io/managed-by: {}
              f:app.kubernetes.io/name: {}
          f:spec:
            .: {}
            f:containers:
              .: {}
              k:{"name":"mariadb"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"MYSQL_ROOT_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                  k:{"name":"MYSQL_ROOT_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                  k:{"name":"POD_IP"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":3306,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities:
                    .: {}
                    f:drop: {}
                  f:runAsGroup: {}
                  f:runAsNonRoot: {}
                  f:runAsUser: {}
                  f:seccompProfile:
                    .: {}
                    f:type: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/run-script"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/scripts"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/lib/mysql"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:initContainers:
              .: {}
              k:{"name":"mariadb-init"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities:
                    .: {}
                    f:drop: {}
                  f:runAsGroup: {}
                  f:runAsNonRoot: {}
                  f:runAsUser: {}
                  f:seccompProfile:
                    .: {}
                    f:type: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/scripts"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/lib/mysql"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:nodeSelector: {}
            f:securityContext:
              .: {}
              f:fsGroup: {}
            f:serviceAccountName: {}
            f:volumes:
              .: {}
              k:{"name":"init-scripts"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
              k:{"name":"run-script"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
        f:updateStrategy:
          .: {}
          f:type: {}
        f:volumeClaimTemplates: {}
    manager: kubedb-provisioner
    operation: Update
    time: "2025-11-06T05:52:02Z"
  - apiVersion: apps.k8s.appscode.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:availableReplicas: {}
        f:collisionCount: {}
        f:currentReplicas: {}
        f:currentRevision: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updateRevision: {}
        f:updatedReplicas: {}
    manager: petset
    operation: Update
    subresource: status
    time: "2025-11-06T05:52:49Z"
  name: mds
  namespace: demo
  ownerReferences:
  - apiVersion: kubedb.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: MariaDB
    name: mds
    uid: dde7ad7f-87fe-44f1-8c7b-d542f8cb1309
  resourceVersion: "942004"
  uid: 971a96a2-fe7d-4be9-be92-c16a9bad2edb
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  podPlacementPolicy:
    name: default
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mds
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mariadbs.kubedb.com
  serviceName: mds-pods
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mds
        app.kubernetes.io/managed-by: kubedb.com
        app.kubernetes.io/name: mariadbs.kubedb.com
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mds-auth
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mds-auth
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: 0.1.acdc.appscode.ninja/ghcr/appscode-images/mariadb:11.5.2-noble@sha256:10acfe8a80c3cbeffb7896305f46dbf270bbc71ef47be92bce81eb8a41503ddb
        imagePullPolicy: IfNotPresent
        name: mariadb
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /scripts
          name: init-scripts
        - mountPath: /run-script
          name: run-script
      initContainers:
      - image: 0.1.acdc.appscode.ninja/ghcr/kubedb/mariadb-init:0.8.0@sha256:b4af1d18118fe9030468c0aa34eb4a44d992e354d0d16acc7380c4caf4509b30
        imagePullPolicy: IfNotPresent
        name: mariadb-init
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /scripts
          name: init-scripts
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 999
      serviceAccountName: mds
      volumes:
      - emptyDir: {}
        name: init-scripts
      - emptyDir: {}
        name: run-script
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: local-path
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
    status: {}
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mds-db658487f
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: mds-db658487f
  updatedReplicas: 1
