apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-infant
  namespace: demo
  labels:
    kubedb.com/kind: MongoDB
spec:
  databaseName: mgo-pvt-reg
  storageSecretName: mg-snap-secret
  gcs:
    bucket: kubedb-qa
  podTemplate:
    spec:
      imagePullSecrets:
      - name: myregistrykey
