apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
  namespace: demo
spec:
  serviceMonitorSelector:
    matchLabels:
      app: kubedb
  version: v1.7.0
  resources:
    requests:
      memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
