#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

# http://uwsgi-docs.readthedocs.io/en/latest/Emperor.html

echo "Starting nginx process..."
# uwsgi --http :8000 --chdir /path/to/your/project --module project.wsgi --virtualenv /path/to/virtualenv
exec uwsgi \
  -s /tmp/pgamin.sock \
  --gid www-data \
  --chmod-socket=777 \
  --processes=5 \
  --enable-threads \
  --chdir /usr/local/lib/python2.7/site-packages/pgadmin4 \
  --manage-script-name \
  --mount /=pgAdmin4:app
