name: update-docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - uses: actions/checkout@v1

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          sudo mv bin/hub /usr/local/bin

      - name: Clone charts repository
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          DOCS_REPOSITORY: ${{ secrets.DOCS_REPOSITORY }}
        run: |
          url="https://${GITHUB_USER}:${GITHUB_TOKEN}@${DOCS_REPOSITORY}.git"
          cd $RUNNER_WORKSPACE
          git clone $url
          cd $(basename $DOCS_REPOSITORY)
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_USER}@appscode.com"

      - name: Update docs
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          DOCS_REPOSITORY: ${{ secrets.DOCS_REPOSITORY }}
        run: |
          export DOCS_ROOT=$RUNNER_WORKSPACE/$(basename $DOCS_REPOSITORY)
          ./hack/gendocs/make.sh
          $DOCS_ROOT/hack/scripts/open-pr.sh
